// ignore_for_file: non_constant_identifier_names

class EventKey {
  static final VALUE = 'VALUE';
  static final TIME = 'TIME';
  static final DWELL = 'DWELL';
  static final INDEX = 'INDEX';
  static final NAME = 'NAME';
  static final TEXT = 'TEXT';
  static final POST_ID = 'POST_ID';
  static final USER_ID = 'USER_ID';
  static final ID = 'ID';
  static final PAGE_TYPE = 'PAGE_TYPE';
}
class Event {
  static final VIEW_VIDEO = "VIEW_VIDEO";
  static final VIDEO_LOADED = "VIDEO_LOADED";
  static final VIEW_PROFILE = "VIEW_PROFILE";
  static final LIKE_VIDEO = "LIKE_VIDEO";
  static final SHARE_VIDEO = "SHARE_VIDEO";
  static final VIDEO_SHARE_WIDGET_PRESS = "VIDEO_SHARE_WIDGET_PRESS";

  static final MAIN_PAGE_BOTTOM_BAR_PRESS = "MAIN_PAGE_BOTTOM_BAR_PRESS";

  static final SETTING_PAGE_MENU_PRESS = "SETTING_PAGE_MENU_PRESS";

  // Login page
  static final LOGIN_PAGE_LOGIN_BUTTON_PRESS = "LOGIN_PAGE_LOGIN_BUTTON_PRESS";
  static final LOGIN_PAGE_FORGOT_PASSWORD_PRESS = "LOGIN_PAGE_FORGOT_PASSWORD_PRESS";
  static final LOGIN_PAGE_SIGN_UP_PRESS = "LOGIN_PAGE_SIGN_UP_PRESS";
  static final LOGIN_PAGE_BACK_PRESS = "LOGIN_PAGE_BACK_PRESS";

  // Sign up page
  static final SIGN_UP_PAGE_USE_PHONE_OR_EMAIL_BUTTON_PRESS = "SIGN_UP_PAGE_USE_PHONE_OR_EMAIL_BUTTON_PRESS";
  static final SIGN_UP_PAGE_TERMS_OF_SERVICE__PRESS = "SIGN_UP_PAGE_TERMS_OF_SERVICE__PRESS";
  static final SIGN_UP_PAGE_PRIVACY_POLICY_PRESS = "SIGN_UP_PAGE_PRIVACY_POLICY_PRESS";
  static final SIGN_UP_PAGE_LOGIN_PRESS = "SIGN_UP_PAGE_LOGIN_PRESS";
  static final SIGN_UP_PAGE_BACK_PRESS = "LOGIN_PAGE_BACK_PRESS";

  // Sign up username page
  static final SIGN_UP_USERNAME_PAGE_NEXT_PRESS = "SIGN_UP_USERNAME_PAGE_NEXT_PRESS";
  static final SIGN_UP_USERNAME_PAGE_BACK_PRESS = "SIGN_UP_USERNAME_PAGE_BACK_PRESS";

  // Sign up password page
  static final SIGN_UP_PASSWORD_PAGE_NEXT_PRESS = "SIGN_UP_PASSWORD_PAGE_NEXT_PRESS";
  static final SIGN_UP_PASSWORD_PAGE_BACK_PRESS = "SIGN_UP_PASSWORD_PAGE_BACK_PRESS";

  // Sign up email page
  static final SIGN_UP_EMAIL_PAGE_TERMS_OF_SERVICE__PRESS = "SIGN_UP_EMAIL_PAGE_TERMS_OF_SERVICE_PRESS";
  static final SIGN_UP_EMAIL_PAGE_PRIVACY_POLICY_PRESS = "SIGN_UP_EMAIL_PAGE_PRIVACY_POLICY_PRESS";
  static final SIGN_UP_EMAIL_PAGE_NEXT_PRESS = "SIGN_UP_EMAIL_PAGE_NEXT_PRESS";
  static final SIGN_UP_EMAIL_PAGE_BACK_PRESS = "SIGN_UP_EMAIL_PAGE_BACK_PRESS";

  // Verification code page
  static final VERIFICATION_CODE_PAGE_CODE_COMPLETE = "VERIFICATION_CODE_PAGE_CODE_COMPLETE";
  static final VERIFICATION_CODE_PAGE_RESEND_PRESS = "VERIFICATION_CODE_PAGE_RESEND_PRESS";
  static final VERIFICATION_CODE_PAGE_BACK_PRESS = "VERIFICATION_CODE_PAGE_BACK_PRESS";
  static final VERIFICATION_CODE_PAGE_LOGIN_PRESS = "VERIFICATION_CODE_PAGE_LOGIN_PRESS";

  // reset password page
  static final RESET_PASSWORD_PAGE_BACK_PRESS = "RESET_PASSWORD_PAGE_BACK_PRESS";
  static final RESET_PASSWORD_PAGE_NEXT_PRESS = "RESET_PASSWORD_PAGE_NEXT_PRESS";

  // Verification code page
  static final RESET_PASSWORD_PASSWORD_PAGE_BACK_PRESS = "RESET_PASSWORD_PASSWORD_PAGE_BACK_PRESS";
  static final RESET_PASSWORD_PASSWORD_PAGE_NEXT_PRESS = "RESET_PASSWORD_PASSWORD_PAGE_NEXT_PRESS";

  // Verification code page
  static final RESET_PASSWORD_VERIFICATION_CODE_PAGE_CODE_COMPLETE = "RESET_PASSWORD_VERIFICATION_CODE_PAGE_CODE_COMPLETE";
  static final RESET_PASSWORD_VERIFICATION_CODE_PAGE_RESEND_PRESS = "RESET_PASSWORD_VERIFICATION_CODE_PAGE_RESEND_PRESS";
  static final RESET_PASSWORD_VERIFICATION_CODE_PAGE_BACK_PRESS = "RESET_PASSWORD_VERIFICATION_CODE_PAGE_BACK_PRESS";
  static final RESET_PASSWORD_VERIFICATION_CODE_PAGE_LOGIN_PRESS = "RESET_PASSWORD_VERIFICATION_CODE_PAGE_LOGIN_PRESS";
}

class EventValue {
  static final NO_OP = 'NO_OP';
}