name: toktik
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  amplify_flutter: ^0.2.0
  amplify_datastore: ^0.2.0
  amplify_api: ^0.2.0
  amplify_auth_cognito: ^0.2.0
  amplify_analytics_pinpoint: ^0.2.0

  cupertino_icons: ^1.0.2
  video_player: ^2.1.4 
  stacked_services: ^0.8.6
  pull_to_refresh: 1.6.4-nullsafety.1
  dio: ^4.0.0-beta6
  get: ^4.1.4
  get_it: ^7.1.3
  like_button: ^2.0.2
  oktoast: ^3.0.0
  marquee: ^2.1.0
  stacked: ^2.1.7
  cached_network_image: ^3.0.0
  event_bus: ^2.0.0
  # 相机插件，还在开发中
  camera: ^0.8.1
  # 图片选择
  image_picker: ^0.8.2
  # 获取视频缩略图
  video_thumbnail: ^0.2.5
  # loading
  flutter_easyloading: ^3.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/video/
    - assets/images/
    - assets/images/splash/breeze_logo.png
    - assets/images/splash/breeze_text.png
  fonts:
    - family:  TikTokIcons
      fonts:
       - asset: assets/fonts/TikTokIcons.ttf

