enum AuthStatus {
  USERNAME_EXISTS,
  INVALID_PASSWORD,
  INVALID_PARAMETER,
  CONFIRM_SIGN_UP_STEP,
  INVALID_SIGN_IN_STATE,
  RESENT_SIGN_UP_CODE_SUCCESSFUL,
  CONFIRM_RESET_PASSWORD_WITH_CODE,
  ALIAS_EXISTS,
  SIGN_UP_DONE,
  SIGN_IN_DONE,
  SIGN_OUT_DONE,
  USER_NOT_FOUND,
  USER_PROFILE_NOT_FOUND,
  CREATE_USER_PROFILE_FAILED,
  NOT_AUTHORIZED,
  INVALID_STATE,
  RESET_PASSWORD_DONE,
  CODE_MISMATCH,
  UNKNOWN
}

extension ParseToString on AuthStatus {
  String toShortString() {
    return this.toString().split('.').last;
  }
}